version: "3.7" 
services:
  php:
    build:
      context: .
    image: phpdocker
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html/ 
    command: php -S 0.0.0.0:9000 -t public/