version: '3.8'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
  web:
    image: php:7.3-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./examples:/var/www/html/
    ports:
      - "80:80"